### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lifeinchords** [gregjopa/music.js#5]
Hi there,
Just found this lib. We're doing sound synthesis with Flocking.js in our [project](https://github.com/parallelsio/core-modules). This would be a great accompaniment to it.

Have you thought about what license to attach? Our project is GPL - is this an issue?
Please lmk.. thanks!
=: s

**Comment by gregjopa** [comment]
I just added a MIT License. Also, I recommend using Teoria.js instead since it is actively maintained and has more features: https://github.com/saebekassebil/teoria

**Comment by lifeinchords** [comment]
Thanks for the tip and heads up! Just integrated Teoria and we're on our way. 
:)

**Comment by gregjopa** [comment]
Good to hear!
